### ISSUE TITLE
Consider removing as it's not used anywhere

### ISSUE THREAD

**Issue by sunminpark94** [COMP2522/project-ruby#234]
https://github.com/COMP2522/project-ruby/blob/566aafcb868ec844683eed598760b0da624ff23b/src/main/java/org/project/KeyHandler.java#L16

**Comment by abhishekchouhannk** [comment]
https://github.com/COMP2522/project-ruby/blob/566aafcb868ec844683eed598760b0da624ff23b/src/main/java/org/project/KeyHandler.java#L8

It might not look like it but being accessed by the player class!! I know it's kind of a weird implementation from our side but

Since we made a keyHandler as its own standalone class, we needed to store the latest keyEvent in some static variable to know what happened (OR what key was pressed last time) and let the player class access it to change player direction.

There wasn't a way to let the player class access it directly. Player would need to extend KeyListener class from the java package to do so, but it didn't feel right to me, so here's some trickery from my side LOL....
And thankfully the delay in storing and reading isn't even perceivable.
